export const fishSpecies = [
  { id: 'guppy', name: 'Guppy', group: 'Livebearer' },
  { id: 'platy', name: 'Platy', group: 'Livebearer' },
  { id: 'molly', name: 'Molly', group: 'Livebearer' },
  { id: 'swordtail', name: 'Swordtail', group: 'Livebearer' },
  { id: 'neon', name: 'Neon Tetra', group: 'Tetra' },
  { id: 'cardinal', name: 'Cardinal Tetra', group: 'Tetra' },
  { id: 'rummy', name: 'Rummy Nose Tetra', group: 'Tetra' },
  { id: 'blackskirt', name: 'Black Skirt Tetra', group: 'Tetra' },
  { id: 'serpae', name: 'Serpae Tetra', group: 'Tetra' },
  { id: 'tiger', name: 'Tiger Barb', group: 'Barb' },
  { id: 'cherry', name: 'Cherry Barb', group: 'Barb' },
  { id: 'rosy', name: 'Rosy Barb', group: 'Barb' },
  { id: 'zebra', name: 'Zebra Danio', group: 'Danio' },
  { id: 'goldfish', name: 'Fancy Goldfish', group: 'Coldwater' },
  { id: 'betta', name: 'Betta (Male)', group: 'Gourami' },
  { id: 'dwarfgourami', name: 'Dwarf Gourami', group: 'Gourami' },
  { id: 'giantgourami', name: 'Giant/Blue Gourami', group: 'Gourami' },
  { id: 'angelfish', name: 'Angelfish', group: 'Cichlid' },
  { id: 'discus', name: 'Discus', group: 'Cichlid' },
  { id: 'ram', name: 'German Blue Ram', group: 'Cichlid' },
  { id: 'apisto', name: 'Apistogramma', group: 'Cichlid' },
  { id: 'oscar', name: 'Oscar', group: 'Cichlid' },
  { id: 'mbuna', name: 'African Cichlid (Mbuna)', group: 'Cichlid' },
  { id: 'cory', name: 'Corydoras Catfish', group: 'Catfish' },
  { id: 'pleco', name: 'Bristlenose Pleco', group: 'Catfish' },
  { id: 'clownloach', name: 'Clown Loach', group: 'Loach' },
  { id: 'kuhli', name: 'Kuhli Loach', group: 'Loach' },
  { id: 'rainbow', name: 'Rainbowfish', group: 'Rainbowfish' },
]

const bad = {
  guppy: ['betta', 'tiger', 'serpae', 'oscar', 'goldfish', 'mbuna', 'giantgourami'],
  platy: ['betta', 'tiger', 'serpae', 'oscar', 'goldfish', 'mbuna', 'giantgourami'],
  molly: ['betta', 'tiger', 'serpae', 'oscar', 'goldfish', 'mbuna', 'giantgourami'],
  swordtail: ['betta', 'tiger', 'serpae', 'oscar', 'goldfish', 'mbuna', 'giantgourami'],
  neon: ['betta', 'tiger', 'serpae', 'angelfish', 'oscar', 'goldfish', 'mbuna', 'giantgourami'],
  cardinal: ['betta', 'oscar', 'goldfish', 'mbuna', 'giantgourami'],
  rummy: ['betta', 'tiger', 'serpae', 'angelfish', 'oscar', 'goldfish', 'mbuna', 'giantgourami'],
  blackskirt: ['betta', 'tiger', 'serpae', 'oscar', 'goldfish', 'mbuna', 'giantgourami'],
  serpae: ['guppy', 'platy', 'molly', 'swordtail', 'neon', 'cardinal', 'rummy', 'betta', 'angelfish', 'discus', 'oscar', 'goldfish', 'mbuna', 'clownloach'],
  tiger: ['guppy', 'platy', 'molly', 'swordtail', 'neon', 'betta', 'angelfish', 'discus', 'oscar', 'goldfish', 'mbuna'],
  cherry: ['oscar', 'goldfish', 'mbuna', 'serpae'],
  rosy: ['oscar', 'goldfish', 'mbuna', 'serpae'],
  zebra: ['oscar', 'goldfish', 'mbuna', 'serpae', 'betta'],
  goldfish: ['guppy', 'platy', 'molly', 'swordtail', 'neon', 'cardinal', 'rummy', 'blackskirt', 'serpae', 'tiger', 'cherry', 'rosy', 'zebra', 'betta', 'angelfish', 'discus', 'oscar', 'mbuna', 'ram', 'apisto', 'dwarfgourami', 'giantgourami', 'clownloach', 'kuhli', 'rainbow'],
  betta: ['guppy', 'platy', 'molly', 'swordtail', 'neon', 'cardinal', 'rummy', 'blackskirt', 'serpae', 'tiger', 'cherry', 'zebra', 'goldfish', 'angelfish', 'discus', 'oscar', 'mbuna', 'ram', 'apisto', 'dwarfgourami', 'giantgourami', 'clownloach', 'rainbow', 'rosy'],
  dwarfgourami: ['betta', 'tiger', 'serpae', 'oscar', 'goldfish', 'mbuna', 'giantgourami'],
  giantgourami: ['guppy', 'platy', 'molly', 'swordtail', 'neon', 'cardinal', 'rummy', 'serpae', 'tiger', 'betta', 'discus', 'oscar', 'goldfish', 'mbuna', 'dwarfgourami'],
  angelfish: ['neon', 'rummy', 'serpae', 'tiger', 'betta', 'goldfish', 'oscar', 'mbuna'],
  discus: ['tiger', 'serpae', 'oscar', 'goldfish', 'mbuna', 'betta', 'giantgourami'],
  ram: ['tiger', 'serpae', 'betta', 'angelfish', 'oscar', 'goldfish', 'mbuna'],
  apisto: ['tiger', 'serpae', 'betta', 'angelfish', 'oscar', 'goldfish', 'mbuna', 'giantgourami'],
  oscar: ['guppy', 'platy', 'molly', 'swordtail', 'neon', 'cardinal', 'rummy', 'blackskirt', 'serpae', 'tiger', 'cherry', 'rosy', 'zebra', 'goldfish', 'betta', 'angelfish', 'discus', 'ram', 'apisto', 'dwarfgourami', 'giantgourami', 'cory', 'clownloach', 'kuhli', 'rainbow'],
  mbuna: ['guppy', 'platy', 'molly', 'swordtail', 'neon', 'cardinal', 'rummy', 'blackskirt', 'serpae', 'tiger', 'cherry', 'rosy', 'zebra', 'goldfish', 'betta', 'angelfish', 'discus', 'ram', 'apisto', 'dwarfgourami', 'giantgourami', 'cory', 'pleco', 'clownloach', 'kuhli', 'rainbow'],
  cory: ['oscar', 'mbuna', 'serpae'],
  pleco: ['oscar', 'mbuna'],
  clownloach: ['oscar', 'mbuna', 'goldfish', 'serpae', 'betta'],
  kuhli: ['oscar', 'mbuna', 'goldfish', 'serpae', 'tiger'],
  rainbow: ['betta', 'oscar', 'mbuna', 'goldfish', 'serpae'],
}

const caution = {
  guppy: ['angelfish', 'discus', 'apisto', 'ram', 'clownloach', 'rainbow'],
  platy: ['angelfish', 'discus', 'apisto', 'clownloach', 'rainbow'],
  molly: ['angelfish', 'discus', 'apisto', 'clownloach', 'rainbow'],
  swordtail: ['angelfish', 'discus', 'apisto', 'clownloach', 'rainbow'],
  neon: ['discus', 'blackskirt', 'dwarfgourami', 'clownloach', 'rainbow'],
  cardinal: ['angelfish', 'tiger', 'serpae', 'discus', 'blackskirt', 'rainbow'],
  rummy: ['discus', 'blackskirt', 'dwarfgourami', 'rainbow'],
  blackskirt: ['angelfish', 'discus', 'dwarfgourami', 'clownloach'],
  serpae: ['blackskirt', 'tiger', 'dwarfgourami', 'giantgourami', 'rainbow', 'cory'],
  tiger: ['serpae', 'blackskirt', 'dwarfgourami', 'giantgourami', 'clownloach', 'rainbow'],
  cherry: ['betta', 'tiger', 'angelfish', 'clownloach', 'rainbow'],
  rosy: ['betta', 'tiger', 'angelfish', 'clownloach', 'rainbow'],
  zebra: ['tiger', 'angelfish', 'clownloach', 'rainbow'],
  goldfish: ['cory', 'pleco'],
  betta: ['cory', 'kuhli', 'pleco'],
  dwarfgourami: ['angelfish', 'apisto', 'ram', 'rainbow'],
  giantgourami: ['angelfish', 'blackskirt', 'cherry', 'rosy', 'zebra', 'rainbow'],
  angelfish: ['guppy', 'cardinal', 'blackskirt', 'cherry', 'rosy', 'zebra', 'dwarfgourami', 'apisto', 'ram'],
  discus: ['guppy', 'platy', 'molly', 'swordtail', 'neon', 'blackskirt', 'zebra', 'apisto', 'angelfish'],
  ram: ['guppy', 'platy', 'molly', 'swordtail', 'neon', 'apisto', 'dwarfgourami'],
  apisto: ['guppy', 'platy', 'molly', 'swordtail', 'neon', 'cardinal', 'ram', 'dwarfgourami', 'discus'],
  oscar: ['rainbow'],
  mbuna: ['pleco', 'rainbow'],
  cory: ['goldfish', 'tiger', 'betta'],
  pleco: ['goldfish', 'tiger', 'serpae'],
  clownloach: ['guppy', 'tiger', 'rainbow', 'discus'],
  kuhli: ['cory'],
  rainbow: ['tiger', 'angelfish', 'clownloach', 'dwarfgourami'],
}

export function getCompat(a, b) {
  if (a === b) return 'same'
  if (bad[a]?.includes(b) || bad[b]?.includes(a)) return 'bad'
  if (caution[a]?.includes(b) || caution[b]?.includes(a)) return 'caution'
  return 'good'
}

export const compatLabel = {
  same: 'Same species',
  good: 'Compatible',
  caution: 'Caution',
  bad: 'Not compatible',
}

export const compatColor = {
  same: 'bg-zinc-300 dark:bg-zinc-600',
  good: 'bg-green-500',
  caution: 'bg-amber-400',
  bad: 'bg-red-500',
}
